// Generated by dts-bundle-generator v9.5.1

import { Engines } from 'surrealdb';

type CapabilitiesAllowDenyList = {
	allow?: boolean | string[];
	deny?: boolean | string[];
};
type ConnectionOptions = {
	strict?: boolean;
	query_timeout?: number;
	transaction_timeout?: number;
	capabilities?: boolean | {
		scripting?: boolean;
		guest_access?: boolean;
		live_query_notifications?: boolean;
		functions?: boolean | string[] | CapabilitiesAllowDenyList;
		network_targets?: boolean | string[] | CapabilitiesAllowDenyList;
	};
};
export declare function surrealdbWasmEngines(opts?: ConnectionOptions): Engines;

export {};
